In [58]:
import numpy as np

In [59]:
import numpy as np
# 1.
a=np.arange(0,1000).reshape(20,50)
print(f"{a[0::3]}\n\n{a[:,-10:]}\n\n{a[a%7==0]}")
a[a>900]=-1
print(f"{a}\n\n{a.flatten()}")



[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
   36  37  38  39  40  41  42  43  44  45  46  47  48  49]
 [150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167
  168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185
  186 187 188 189 190 191 192 193 194 195 196 197 198 199]
 [300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317
  318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335
  336 337 338 339 340 341 342 343 344 345 346 347 348 349]
 [450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
  468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
  486 487 488 489 490 491 492 493 494 495 496 497 498 499]
 [600 601 602 603 604 605 606 607 608 609 610 611 612 613 614 615 616 617
  618 619 620 621 622 623 624 625 626 627 628 629 630 631 632 633 634 635
  636 637 638 639 640 64

In [ ]:
# 2.
A=np.random.randint(0,100,(200,5))
B=np.random.randint(-5,6,(1,5))
print(f"{A}\n\n{B}")
A_norm=(A-A.mean(axis=0))/A.std(axis=0)
print(f"\n\n{A_norm}")
A_BONUS=A_norm+B
print(f"\n\n{A_BONUS}")
mean_per_subject=A_BONUS.mean(axis=0)
std_per_subject=A_BONUS.std(axis=0)

print(f"\n\n{mean_per_subject}\n\n{std_per_subject}\n\n{A_BONUS.max(axis=0)}\n\n{A_BONUS.min(axis=0)}\n\n")

count=(A_BONUS > (mean_per_subject+1.5*std_per_subject)).sum(axis=0)
print(count)
A_final=np.clip(A_BONUS,-2,+2)
print(f"\n\n{A_final}")

In [96]:
rl=np.random.rand(500,20)
print(f"{rl}\n\n")
rl_center=rl-rl.mean(axis=0)
print(f"{rl_center}\n\n")
rl_cov=np.cov(rl_center,rowvar=False)
print(rl_cov)
vals,vecs=np.linalg.eig(rl_cov)
vals.sort()
print(f"\n\n{vals}")

[[0.67243893 0.54781889 0.9940333  ... 0.08663636 0.13801895 0.14946265]
 [0.34884154 0.62657352 0.10403508 ... 0.43403661 0.37346382 0.03745854]
 [0.08555074 0.31019212 0.16823618 ... 0.0013435  0.77340807 0.24544684]
 ...
 [0.26558711 0.91403644 0.11071226 ... 0.6048245  0.79334841 0.80012539]
 [0.27765798 0.82925463 0.14374701 ... 0.85371268 0.91643626 0.59536662]
 [0.08114612 0.84054575 0.87059798 ... 0.00369905 0.31869128 0.64422773]]


[[ 0.16154943  0.04230183  0.49248504 ... -0.42083444 -0.35507103
  -0.34873054]
 [-0.16204796  0.12105646 -0.39751317 ... -0.07343419 -0.11962616
  -0.46073465]
 [-0.42533877 -0.19532495 -0.33331208 ... -0.5061273   0.28031809
  -0.25274635]
 ...
 [-0.2453024   0.40851937 -0.390836   ...  0.09735371  0.30025843
   0.30193221]
 [-0.23323152  0.32373757 -0.35780125 ...  0.34624188  0.42334628
   0.09717343]
 [-0.42974339  0.33502868  0.36904972 ... -0.50377175 -0.1743987
   0.14603454]]


[[ 8.56452801e-02 -3.21492739e-03 -2.28453725e-03 -5.23083551